gui:
  showIcons: true
  nerdFontsVersion: "3"
git:
  paging:
    colorArg: always
    # pager: delta --dark --paging=never --no-gitconfig
    # externalDiffCommand: difft --color=always --display=inline
    externalDiffCommand: difft --color=always
