-- TODO: put everything in the M convention and call config() or somerhing
require('core.config')
require('core.commands').config()

require('plugins.lsp.nvim-lspconfig').config()
require('plugins.lsp.null-ls.init').config()

local autocmds = require('core.autocommands')
autocmds.define_augroups(autocmds.autocommands)

require('plugins.nvim-cmp').config()
require('plugins.nvim-treesitter').config()
require('plugins.nvim-web-devicons').config()
require('plugins.lualine.init').config()
require('plugins.startify').config()
require('plugins.neoscroll').config()
require('plugins.telescope').config()
require('plugins.luasnip').config()
require('plugins.nvim-autopairs').config()
require('plugins.indent-blankline').config()
require('plugins.hop').config()
require('plugins.markdown-preview').config()
require('plugins.vim-asterisk').config()
require('plugins.vim-easy-align').config()
require('plugins.vim-fugitive').config()
require('plugins.vim-yoink').config()
-- require('plugins.wilder').config()
require('plugins.clever-f').config()
require('plugins.splitjoin').config()
require('plugins.which-key').config()
require('plugins.abolish').config()
require('plugins.nvim-tree').config()
require('plugins.barbar').config()
require('plugins.gitsigns').config()

require('plugins.dap.nvim-dap').config()
require('plugins.dap.nvim-dap-ui').config()

require('core.keymappings').setup()
