theme = "custom_gruvbox_dark_hard"

[editor]
line-number = "relative"
true-color = true
cursorline = true
color-modes = true
shell = ["fish"]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "file-type"]

[editor.indent-guides]
render = true

[keys.normal]
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
C = ["collapse_selection", "extend_to_line_end", "change_selection"]
D = ["extend_to_line_end", "delete_selection"]
S = "surround_add"
V = ["select_mode", "extend_to_line_bounds"]
";" = "repeat_last_motion"
"'" = "collapse_selection"
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
esc = ["collapse_selection", "keep_primary_selection"]
"C-n" = "copy_selection_on_next_line"
"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"
"H" = "goto_previous_buffer"
"L" = "goto_next_buffer"

[keys.insert]
j = { k = "normal_mode", K = "normal_mode" }
J = { k = "normal_mode", K = "normal_mode" }
k = { j = "normal_mode", J = "normal_mode" }
K = { j = "normal_mode", J = "normal_mode" }
esc = ["collapse_selection", "normal_mode"]

[keys.select]
o = "flip_selections"
";" = "repeat_last_motion"
V = ["normal_mode", "collapse_selection"]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"C-n" = ["split_selection_on_newline", "normal_mode"]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
